### задание 1

In [3]:
import numpy as np

In [8]:
a = np.array([[1, 6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]
             ])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [6]:
mean_a = a.mean(axis=0)
print(mean_a)

array([2. , 8.4])

## Задание 2

In [9]:
a_centered = a-mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 3

In [25]:
a_centered_sp = a_centered[:][0]@(a_centered[:][1])
b=a_centered_sp/(a.shape[0]-1)
print (a_centered_sp)
print (b)

0.960000000000001
0.24000000000000024
